check for empty result in list_wallets
algorand/py-algorand-sdk pull request #149
Opened 2020-09-29 01:26 UTC by mjiang102628

2020-09-29 02:43 UTC, EvanJRichard approved these changes

2020-09-30 13:51 UTC, jasonpaulos requested changes

2020-09-30 13:51 UTC, jasonpaulos commented on algosdk/kmd.py
> +            return res
It's probably better to return an empty list if there are no wallets.

2020-10-02 13:27 UTC, jasonpaulos approved these changes

2020-10-02 13:28 UTC, merged