update langspec
algorand/py-algorand-sdk pull request #197
Opened 2021-06-07 14:03 UTC by shiqizng

Regenerate langspec.json to include latest TealV4 opcodes.

2021-06-07 20:38 UTC, jdtzmn approved these changes

2021-06-07 20:41 UTC, jdtzmn requested changes

2021-06-07 20:41 UTC, jdtzmn commented on algosdk/data/langspec.json
> +{"EvalMaxVersion":4,"LogicSigVersion":3,"Ops":[{"Opcode":0,"Name":"err","Cost":1,"Size":1,"Doc":"Error. Panic immediately. This is primarily a fencepost against accidental zero bytes getting compiled
nit: keep newline at end of file

2021-06-09 14:25 UTC, jdtzmn approved these changes

2021-06-11 20:50 UTC, jasonpaulos requested changes

2021-06-11 20:50 UTC, jasonpaulos commented on test_unit.py
> +        self.assertTrue(logic.spec['LogicSigVersion'] >= 3)
```suggestion
```
Could you just remove this check?

2021-06-11 20:55 UTC, jasonpaulos approved these changes
Pending tests, looks good to merge.

2021-06-14 13:47 UTC, merged